# @package _global_

# overfits to 1 batches

trainer:
  gpus: 1
  max_epochs: 800
  overfit_batches: 1
  log_every_n_steps: 1
  strategy: null
  sync_batchnorm: True

datamodule:
  batch_size: 1
  num_workers: 10
  pin_memory: True
  persistent_workers: True

scheduler:
  step_size: 1000

logger:
  tensorboard:
    save_dir: ${oc.env:DEBUG_SAVEDIR}
