_target_: pytorch_lightning.Trainer

gpus: 0

accumulate_grad_batches: 2

min_epochs: 1
max_epochs: 30

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null

track_grad_norm: -1



